name: CI   

on: [push, pull_request]  

jobs:
  build:                   
    runs-on: ubuntu-latest  

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'


      - name: Install deps
        run: pip install -r requirements.txt
        

      - name: Run tests
        run: python --version
      - name: Run Flake8 Linter
        run: |
          flake8 src/

      - name: Run Pytest
        run: |
          pytest tests/ --maxfail=1 --disable-warnings -v